config/routes.rb
Rails.application.routes.draw do
  # Root route based on authentication
  devise_scope :user do
    authenticated :user do
      root 'posts#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # Routes for users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users
  resources :friends, only: %i[index]

  # Routes for post-system
  resources :posts do
    resources :comments, only: %i[create destroy]
    resource :like, only: %i[create destroy]
  end

  # Routes for friendship-system
  resources :friend_requests, only: %i[index create destroy] do
    post :accept, on: :member
    post :decline, on: :member
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[github]

  validates :username, presence: true

  # Friendship-system associations
  has_many :outgoing_friend_requests, class_name: 'FriendRequest',
                                      foreign_key: :requester_id,
                                      dependent: :destroy
  has_many :incoming_friend_requests, class_name: 'FriendRequest',
                                      foreign_key: :requestee_id,
                                      dependent: :destroy

  # Post-system associations
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # Avatar associations
  has_one_attached :avatar, dependent: :destroy
  after_commit :add_default_avatar, on: %i[create update]

  # Callback for sending welcome email
  after_create :send_welcome_email

  # Scope to query for users which are not friends of a given user
  scope :not_friends_with, -> (user) { where.not(id: user.friends_ids + [user.id]) }
  scope :filter_by_name, -> (name) { where('lower(username) LIKE ?', "%#{User.sanitize_sql_like(name)}%") }

  # Find or create new user using Omniauth
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.username = auth.info.nickname
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  # Return array of user friends ids
  def friends_ids
    accepted_frs = FriendRequest.accepted_friend_requests(self)
    accepted_frs.map { |fr| fr.requester_id == id ? fr.requestee_id : fr.requester_id }
  end

  # Return array of user pending friends ids
  def pending_friends_ids
    pending_frs = FriendRequest.pending_friend_requests(self)
    pending_frs.map { |fr| fr.requester_id == id ? fr.requestee_id : fr.requester_id }
  end  

  # Return array of user friends (users)
  def friends
    User.where(id: friends_ids)
  end

  # Check whether User is friends with another User, returns true or false
  def friends_with?(user)
    FriendRequest.friends?(self, user)
  end

  # Check if user has a pending friend request with another user, returns true or false
  def pending_friend_request?(user)
    friend_requests = FriendRequest.pending_friend_requests(self)
    friend_requests = friend_requests.map { |fr| fr.requester_id == id ? fr.requestee_id : fr.requester_id }
    friend_requests.include?(user.id)
  end

  # Check if user has any incoming friend requests, returns true or false
  def incoming_friend_requests?
    return false if incoming_friend_requests_count.nil? || incoming_friend_requests_count.zero?

    true
  end

  private

  # Add default avatar to user if no avatar attached
  def add_default_avatar
    unless avatar.attached?
      avatar.attach(
        io: File.open(
          Rails.root.join(
            'app', 'assets', 'images', 'default_avatar.png'
          )
        ), filename: 'default_avatar.png',
        content_type: 'image/png'
      )
    end
  end

  # Send out welcome email to user using UserMailer
  def send_welcome_email
    UserMailer.with(user: self).welcome_email.deliver_now
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :github

  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth'].except(:extra)
      errors = @user.errors.full_messages.to_sentence.downcase
      flash[:alert] = "Could not authenticate you from Github because #{errors}" if is_navigational_format?
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # Overwrite update_resource to let users to update their user without giving their password
  def update_resource(resource, params)
    if current_user.provider == 'github'
      params.delete('current_password')
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.not_friends_with(current_user)
                 .with_attached_avatar
    @users = @users.filter_by_name(params[:q]) if params[:q].present?

    @pending_friends_ids = current_user.pending_friends_ids
  end

  def show
    @user = User.find(params[:id])
    @friendship_status = FriendRequest.where(requester_id: [current_user, @user])
                                      .where(requestee_id: [current_user, @user])
    @posts = Post.timeline_by_users(@user)
    @new_comment = Comment.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :bio, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar.html.erb
<div class="has-text-centered">
  <figure class="image is-128x128 is-inline-block">
    <% if user.avatar.attached? %>
      <%= image_tag user.avatar.variant(resize_to_fill: [128, 128]), class: "is-rounded" %>
    <% end %>
  </figure>
</div>

app/views/users/_user.html.erb
<div class="box">
  <article class="media">
    <figure class="media-left m-0">
      <p class="image is-64x64">
        <%= image_tag user.avatar.variant(resize_to_fill: [64, 64]), class: "is-rounded" %>
      </p>
    </figure>
    <div class="media-content has-text-centered">
      <h5><%= link_to user.username, user, class: "has-text-dark" %></h5>
      <% if @pending_friends_ids.include?(user.id) %>
        <%= link_to "Pending Request", friend_requests_path, class: "button is-light is-responsive" %>
      <% else %>
        <%= button_to "Send Friend Request", friend_requests_path(requestee_id: user), method: :post, data: { turbo_method: :post }, class: "button is-link is-responsive" %>
      <% end %>
    </div>
  </article>
</div>

app/views/users/_user_form.html.erb
<%= form_with model: @user do |form| %>
  <%= render "devise/shared/error_messages", resource: @user %>
  <div class="field">
    <%= form.label :username, class: "label" %>
    <div class="control">
      <%= form.text_field :username, class: "input" %>
    </div>
  </div>
  <div class="field">
    <%= form.label :bio, class: "label" %>
    <div class="control">
      <%= form.text_area :bio, class: "textarea" %>
    </div>
  </div>
  <div class="file has-name mb-3" data-controller="upload">
    <%= form.label :avatar, class: "file-label" do %>
      <%= form.file_field :avatar, class: "file-input", data: { action: "change->upload#display", upload_target: "input" } %>
      <span class="file-cta">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          Change avatar...
        </span>
      </span>
      <span class="file-name" data-upload-target="output">
        No file selected.
      </span>
    <% end %>
  </div>
  <div class="field">
    <div class="control">
      <%= form.submit class: "button is-link" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="columns is-centered">
    <div class="column has-text-centered">
      <%= render 'avatar', user: @user %>
    </div>
    <div class="column is-two-thirds">
      <div class="mb-3"><%= render 'user_form', user: @user %></div>
      <div class="mb-1"><%= link_to "Change email/password or cancel account", edit_user_registration_path %></div>
      <div><%= link_to "Back", :back %></div>
    </div>
    <div class="column"></div>
  </div>
</div>

app/views/users/index.html.erb
<div class="columns is-gapless">
  <div class="column"></div>
  <div class="column is-two-thirds mw-600">
    <%= render 'shared/search_form' %>
    <%= render @users %>
  </div>
  <div class="column"></div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="columns">
    <div class="column has-text-centered">
      <%= render 'avatar', user: @user %>
      <% if current_user == @user %>
        <%= link_to "Edit Profile", edit_user_path(@user), class: "button is-link" %>
      <% elsif @friendship_status.empty? %>
        <%= button_to "Send Friend Request", friend_requests_path(requestee_id: @user), method: :post, data: { turbo_method: :post }, class: "button is-link" %>
      <% elsif @friendship_status.first.accepted %>
        <%= button_to "Remove Friend", @friendship_status.first, method: :delete, form: { data: { turbo_method: :delete, turbo_confirm: "Are you sure you want unfriend?" } }, class: "button is-danger" %>
      <% else %>
        <%= link_to "Pending Friend Request", friend_requests_path, class: "button is-light" %>
      <% end %>
    </div>
    <div class="column is-two-thirds mw-1200">
      <div class="content">
        <h1><%= @user.username %></h1>
        <p><%= simple_format(@user.bio) %></p>
        <% if current_user == @user || (!@friendship_status.first.nil? && @friendship_status.first.accepted) %>
          <h3>Recent Posts</h3>
          <%= render @posts, new_comment: @new_comment%>
        <% end %>
      </div>
    </div>
    <div class="column"></div>
  </div>
</div>