config/routes.rb
Rails.application.routes.draw do
  # Root route based on authentication
  devise_scope :user do
    authenticated :user do
      root 'posts#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # Routes for users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users
  resources :friends, only: %i[index]

  # Routes for post-system
  resources :posts do
    resources :comments, only: %i[create destroy]
    resource :like, only: %i[create destroy]
  end

  # Routes for friendship-system
  resources :friend_requests, only: %i[index create destroy] do
    post :accept, on: :member
    post :decline, on: :member
  end
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :requester, class_name: 'User'
  belongs_to :requestee, class_name: 'User'

  validates :requester_id, uniqueness: { scope: :requestee_id, message: 'friend request already exists' }
  validate :check_self_friend_request

  # Callbacks to update conditional counter
  after_save :update_incoming_friend_requests_count
  after_destroy :update_incoming_friend_requests_count

  # Scope to query all accepted friend requests for a certain user (i.e., their friends)
  scope :accepted_friend_requests, ->(user) {
    where('accepted = true AND (requester_id = ? OR requestee_id = ?)',
          user.id, user.id)
  }

  scope :pending, -> { where(accepted: false) }

  # Scope to query all pending friend requests for a certain user
  scope :pending_friend_requests, ->(user) {
    where('accepted = false AND (requester_id = ? OR requestee_id = ?)',
          user.id, user.id)
  }

  def self.friends?(user1, user2)
    users = [user1, user2]
    where(accepted: true).where(requester_id: users).where(requestee_id: users).present?
  end

  private

  def update_incoming_friend_requests_count
    requestee.update_attribute(:incoming_friend_requests_count,
                               FriendRequest.where(accepted: false)
                               .where(requestee: requestee).count)
  end

  def check_self_friend_request
    errors.add(:requester_id, "can't be friend with self") if requester == requestee
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :verify_user_friend_request, only: %i[accept decline]

  def index
    @incoming_friend_requests = current_user.incoming_friend_requests.pending
                                            .includes({ requester: [{ avatar_attachment: :blob }] })
    @outgoing_friend_requests = current_user.outgoing_friend_requests.pending
                                            .includes({ requestee: [{ avatar_attachment: :blob }] })
  end

  def create
    @friend_request = current_user.outgoing_friend_requests.build(requestee_id: params[:requestee_id])

    flash[:alert] = 'Ahh, something went wrong! We could not send a new friend request' unless @friend_request.save

    redirect_back(fallback_location: root_path)
  end

  def accept
    @friend_request = FriendRequest.find(params[:id])

    if @friend_request.update(accepted: true)
      flash[:notice] = 'Friend request accepted!'
    else
      flash[:alert] = 'Ahh, something went wrong! Friend request could not be accepted'
    end

    redirect_to friend_requests_path
  end

  def decline
    @friend_request = FriendRequest.find(params[:id])

    flash[:alert] = if @friend_request.destroy
                      'Friend request declined!'
                    else
                      'Ahh, something went wrong! Friend request could not be declined'
                    end

    redirect_to friend_requests_path
  end

  def destroy
    @friend_request = FriendRequest.find(params[:id])
    @friend_request.destroy

    redirect_back(fallback_location: root_path)
  end

  private

  def verify_user_friend_request
    friend_request = FriendRequest.find(params[:id])
    return if current_user == friend_request.requestee

    flash[:alert] = 'You do not have the correct permissions to do this'
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_friend_request.html.erb
<div class="box">
  <h5><%= friend_request.requester.email %></h5>
  <%= button_to "Accept", accept_friend_request_path(friend_request), method: :post, data: { turbo_method: :post } %>
  <%= button_to "Decline", decline_friend_request_path(friend_request), method: :post, data: { turbo_method: :post } %>
</div>

app/views/friend_requests/_incoming_friend_request.html.erb
<div class="box">
  <article class="media">
    <figure class="media-left m-0">
      <p class="image is-64x64">
        <%= image_tag incoming_friend_request.requester.avatar.variant(resize_to_fill: [64, 64]), class: "is-rounded" %>
      </p>
    </figure>
    <div class="media-content has-text-centered">
      <h5><%= link_to incoming_friend_request.requester.username, incoming_friend_request.requester, class: "has-text-dark" %></h5>
      <div class="field is-grouped is-flex is-justify-content-center">
        <div class="control mr-2"><%= button_to "Accept", accept_friend_request_path(incoming_friend_request), method: :post, data: { turbo_method: :post }, class: "button is-link is-responsive" %></div>
        <div class="control"><%= button_to "Decline", decline_friend_request_path(incoming_friend_request), method: :post, data: { turbo_method: :post }, class: "button is-light is-responsive" %></div>
      </div>
    </div>
  </article>
</div>

app/views/friend_requests/_outgoing_friend_request.html.erb
<div class="box">
  <article class="media">
    <figure class="media-left m-0">
      <p class="image is-64x64">
        <%= image_tag outgoing_friend_request.requestee.avatar.variant(resize_to_fill: [64, 64]), class: "is-rounded" %>
      </p>
    </figure>
    <div class="media-content has-text-centered">
      <h5><%= link_to outgoing_friend_request.requestee.username, outgoing_friend_request.requestee, class: "has-text-dark" %></h5>
      <%= button_to "Cancel", friend_request_path(outgoing_friend_request), method: :delete, data: { turbo_method: :delete }, class: "button is-light is-responsive" %>
    </div>
  </article>
</div>

app/views/friend_requests/index.html.erb
<div class="columns is-gapless">
  <div class="column"></div>
  <div class="column is-two-thirds mw-600">
    <div class="content">
      <h2>Incoming Friend Requests</h2>
      <% if @incoming_friend_requests.exists? %>
        <%= render partial: 'incoming_friend_request', collection: @incoming_friend_requests %>
      <% else %>
        No incoming friend requests
      <% end %>
    </div>
    <div class="content">
      <h2>Pending Friend Requests</h2>
      <% if @outgoing_friend_requests.exists? %>
        <%= render partial: 'outgoing_friend_request', collection: @outgoing_friend_requests %>
      <% else %>
        No pending friend requests
      <% end %>
    </div>
  </div>
  <div class="column"></div>
</div>