config/routes.rb
Rails.application.routes.draw do
  # Root route based on authentication
  devise_scope :user do
    authenticated :user do
      root 'posts#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # Routes for users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users
  resources :friends, only: %i[index]

  # Routes for post-system
  resources :posts do
    resources :comments, only: %i[create destroy]
    resource :like, only: %i[create destroy]
  end

  # Routes for friendship-system
  resources :friend_requests, only: %i[index create destroy] do
    post :accept, on: :member
    post :decline, on: :member
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :photo

  validates :body, presence: true, unless: :photo_attached?

  scope :posted_by, -> (users) { where user: users }
  scope :with_likes, -> { includes(:likes) }
  scope :with_comments, -> { includes({ comments: [{ user: [{ avatar_attachment: :blob }] }] }) }
  scope :with_user, -> { includes({ user: [{ avatar_attachment: :blob }] })}
  scope :timeline_by_users, -> (users) { includes({ photo_attachment: :blob }).with_comments.with_likes.with_user
                                                                              .posted_by(users).order('created_at DESC') }

  enum status: %i[unedited edited]

  before_update :set_edit_status if unedited

  def liked?
    return false if self.likes_count.nil? || self.likes_count.zero?

    true
  end

  def liked_by?(user)
    liked_by = likes.collect(&:user_id)
    liked_by.include?(user.id)
  end

  private

  def photo_attached?
    photo.attached?
  end

  def set_edit_status
    self.status = 'edited' if changed?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :verify_post_author, only: %i[edit update destroy]
  before_action :create_new_comment, only: %i[index show create]

  def index
    @posts = Post.timeline_by_users(current_user.friends_ids + [current_user.id])
  end

  def show
    @post = Post.with_likes.with_comments.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.turbo_stream { render turbo_stream: turbo_stream.prepend('posts', @post) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@post) }
      format.html { redirect_to posts_path, status: 303 }
    end
  end

  private

  def post_params
    params.require(:post).permit(:body, :photo)
  end

  def verify_post_author
    @post = Post.find(params[:id])
    return if current_user == @post.user

    flash[:alert] = 'You do not have the correct permissions to do this'
    redirect_to posts_path
  end

  def create_new_comment
    @new_comment = Comment.new
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<%= turbo_frame_tag post do %>
  <div class="box mb-4">
    <article class="media">
      <figure class="media-left ml-1">
        <p class="image is-64x64">
          <%= image_tag post.user.avatar.variant(resize_to_fill: [64, 64]), class: "is-rounded" %>
        </p>
      </figure>
      <div class="media-content">
        <div class="content">
          <p>
            <strong><%= link_to post.user.username, post.user, class: "has-text-dark", data: { turbo_frame: "_top"} %></strong><br>
            <small>Posted <%= time_ago_in_words(post.created_at) %> ago <%= "· Edited" if post.edited? %></small>
          </p>
        </div>
      </div>
      <div class="media-right">
        <% if user_signed_in? && current_user == post.user %>
          <%= render 'posts/post_controls', post: post %>
        <% end %>
      </div>
    </article>
    <%= image_tag post.photo, class: "mb-3", style: "max-height: 500px" if post.photo.attached? %>
    <%= simple_format(post.body) %>
    <hr>
    <nav class="level is-mobile mb-0">
      <div class="level">
        <%= turbo_frame_tag "post_#{post.id}_likes" do %>
          <%= render 'posts/post_likes', post: post %>
        <% end %>
      </div>
    </nav>
    <hr>
    <div id=<%= "post_#{post.id}_comments" %> class="mb-5">
      <% post.comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment, post: post %>
      <% end %>
    </div>
    <%= render 'comments/comment_form', comment: @new_comment, post: post %>
  </div>
<% end %>

app/views/posts/_post_controls.html.erb
<div class="level-right">
  <div class="level-item">
    <%= link_to edit_post_path(post), class: "has-text-dark" do %>
      <i class="far fa-edit" alt="edit"></i>
    <% end %>
  </div>
  <div class="level-item">
    <%= link_to post, class: "has-text-dark", method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this post?" } do %>
      <i class="far fa-trash-alt" alt="delete"></i>
    <% end %>
  </div>
</div>

app/views/posts/_post_feed.html.erb
<% posts.each do |post| %>
  <div class="box">
    <div class="content">
      <h5><%= post.user.email %></h5>
      <p><%= simple_format(post.body) %></p>
    </div>
    <%= render 'post_likes', post: post %>
    <hr>
    <% post.comments.each do |comment| %>
      <div class="content">
        <h6><%= comment.user.email %></h6>
        <p><%= simple_format(comment.body) %></p>
      </div>
    <% end %>
    <div>
      <%= form_with model: [post, comment] do |comment_form| %>
        <div class="field has-addons">
          <div class="control is-expanded">
            <%= comment_form.label :body, class: "is-hidden" %>
            <%= comment_form.text_field :body, class: "input is-fullwidth", placeholder: "Leave a comment..." %>
          </div>
          <div class="control">
            <%= comment_form.submit class: "button is-link" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/_post_form.html.erb
<div class="box mb-5">
  <%= form_with model: post, data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } do |form| %>
    <div class="field">
      <div class="control">
        <%= form.label :body, class: "is-hidden" %>
        <%= form.text_area :body, class: "textarea", placeholder: "What's on your mind?", data: { reset_form_target: "post" } %>
      </div>
      <% if post.errors.any? %>
        <% post.errors.full_messages.each do |msg| %>
          <p class="help is-danger mt-3"><%= msg %></p>
        <% end %>
      <% end %>
    </div>
      <% if post.new_record? %>
        <div class="field">
          <div class="file has-name mb-3" data-controller="upload">
            <%= form.label :photo, class: "file-label" do %>
              <%= form.file_field :photo, class: "file-input", data: { action: "change->upload#display submit->upload#reset", upload_target: "input" } %>
              <span class="file-cta">
                <span class="file-icon">
                  <i class="fas fa-upload"></i>
                </span>
                <span class="file-label">
                  Add photo...
                </span>
              </span>
              <span class="file-name" data-upload-target="output" data-reset-form-target="upload">
                No file selected.
              </span>
            <% end %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= form.submit class: "button is-link" %>
          </div>
        </div>
      <% else %>
        <div class="field is-grouped">
          <div class="control">
            <%= form.submit class: "button is-link" %>
          </div>
          <div class="controls">
            <%= link_to "Cancel", :back, class: "button is-light" %>
          </div>
        </div>
      <% end %>
  <% end %>
</div>

app/views/posts/_post_likes.html.erb
<% if post.liked? %>
  <%= "#{post.likes_count} #{"person".pluralize(post.likes_count)} #{post.likes_count > 1 ? 'like' : 'likes' } this" %>
<% end %>
<% if post.liked_by?(current_user) %>
  <%= link_to post_like_path(post), class: "has-text-dark", method: :delete, data: { turbo_method: :delete } do %>
    <i class="fas fa-thumbs-up" alt="unlike"></i>
  <% end %>
<% else %>
  <%= link_to post_like_path(post), class: "has-text-dark", method: :post, data: { turbo_method: :post } do %>
    <i class="far fa-thumbs-up" alt="like"></i>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag @post do %>
  <%= render 'post_form', post: @post %>
<% end %>

app/views/posts/index.html.erb
<div class="columns is-gapless">
  <div class="column"></div>
  <div class="column is-two-thirds mw-1200">
    <%= turbo_frame_tag id= "new_post", src: new_post_path %>
    <div id="posts">
      <%= render @posts %>
    </div>
  </div>
  <div class="column"></div>
</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag id="new_post" do %>
  <%= render 'post_form', post: @post %>
<% end %>

app/views/posts/show.html.erb
<div class="columns is-gapless">
  <div class="column"></div>
  <div class="column is-two-thirds">
    <%= render @post, new_comment: @new_comment %>
  </div>
  <div class="column"></div>
</div>