config/routes.rb
Rails.application.routes.draw do
  # Root route based on authentication
  devise_scope :user do
    authenticated :user do
      root 'posts#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # Routes for users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users
  resources :friends, only: %i[index]

  # Routes for post-system
  resources :posts do
    resources :comments, only: %i[create destroy]
    resource :like, only: %i[create destroy]
  end

  # Routes for friendship-system
  resources :friend_requests, only: %i[index create destroy] do
    post :accept, on: :member
    post :decline, on: :member
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceBuddies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar mb-4" role="navigation" aria-label="main navigation" data-controller="navbar">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <%= image_tag 'left_buddy.png' %>
        <% end %>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-navbar-target="burger" data-action="navbar#toggle">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu" data-navbar-target="menu">
        <div class="navbar-start">
          <%= link_to "Home", root_path, class: "navbar-item" %>
          <% if user_signed_in? %>
            <%= link_to "Profile", user_path(current_user), class: "navbar-item" %>
            <%= link_to "Friends", friends_path, class: "navbar-item" %>
          <% end %>
        </div>
        <div class="navbar-end">
          <% if user_signed_in? %>
            <%= link_to "Find New Friends", users_path, class: "navbar-item" %>
            <%= link_to friend_requests_path, class: "navbar-item" do %>
              Friend Requests
                <% if current_user.incoming_friend_requests? %>
                  <span class="tag is-danger ml-2"><%= current_user.incoming_friend_requests_count %></span>
                <% end %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "navbar-item" %>
          <% else %>
            <div class="navbar-item">
              <div class="buttons">
                <%= link_to new_user_registration_path, class: "button is-primary" do %>
                  <strong>Sign up</strong>
                <% end %>
                <%= link_to "Log in", new_user_session_path, class: "button is-light"%>
                <%= button_to user_github_omniauth_authorize_path, class: "button is-light mb-2", data: { turbo: "false" } do %>
                  <i class="fab fa-github"></i><span class="ml-2">Sign in with Github</span>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container mb-4">
      <% if flash[:alert] %>
        <article class="message is-danger">
          <div class="message-body">
            <%= alert %>
          </div>
        </article>
      <% end %>
      <% if flash[:notice] %>
        <article class="message is-success">
          <div class="message-body">
            <%= notice %>
          </div>
        </article>
      <% end %>
    </div>

    <div class="flex-wrapper">
      <div class="content px-3"><%= yield %></div>
      <footer class="footer">
        <div class="content has-text-centered">
          <p>
            <strong>FaceBuddies</strong> by <a href="https://github.com/ayrt-n">Ayrton Parkinson <i class="fab fa-github"></i></a>
          </p>
        </div>
      </footer>
    </div>
  </body>
</html>